export const WINDOW_HEIGHT_THRESHOLD = 700;

// Modal cursor constants
export const CURSOR_STYLE_CONFIG = {
  MIN_WIDTH: 128,
  MAX_WIDTH: 180,
  ARROW_SPACE: 40,
  LARGE_FONT_SIZE: 18,
  SMALL_FONT_SIZE: 12,
  LARGE_CHAR_WIDTH: 10,
  SMALL_CHAR_WIDTH: 7,
};
