export const CITIES = [
  "BARCELONA",
  "LONDON",
  "MELBOURNE",
  "NEW_YORK",
  "PARIS",
  "TOKYO",
];

export const TICKER_CONFIG = {
  MIN_ROW_HEIGHT: 120,
  ROW_MARGIN: 32,
  DUPLICATE_COUNT: 200,
  SAFETY_BUFFER: 20,
  BOTTOM_MARGIN: 80,
} as const;
