export const CITIES = [
  "ANDALUSIA",
  "BARCELONA",
  "NULLARBOR",
  "PORTUGAL",
  "VIETNAM"
];

export const TICKER_CONFIG = {
  MIN_ROW_HEIGHT: 120,
  ROW_MARGIN: 32,
  DUPLICATE_COUNT: 200,
  SAFETY_BUFFER: 20,
  BOTTOM_MARGIN: 80,
} as const;
